### ISSUE TITLE
if and else statements

### ISSUE THREAD

**Issue by annaqharder** [learn-co-curriculum/phase-0-pac-2-selection-with-conditionals#5]
### Canvas Link

https://learning.flatironschool.com/courses/6106/pages/selection-with-conditionals-the-if-statement?module_item_id=471003

### Concern

The REPL example window doesn't show the if and else structure code when "Run" is pressed. It only shows "true" or "false". 
<img width="488" alt="Screen Shot 2022-09-21 at 4 58 29 PM" src="https://user-images.githubusercontent.com/112916287/191624715-986f605e-53db-4e26-ba44-d19a83246c7b.png">

**Comment by jlboba** [comment]
Hello, thanks for raising this issue. If you click on the "Show files" button, you will be 
able to open up the `index.js` file to see the `if/else` structure.
 
However, I agree that initially it isn't very clear and we will look into how to immediately 
display the code rather than the output.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
